# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vuepress-build-docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install -D "vuepress@next"
    - run: npm install -D "@vuepress/plugin-search@next"
    - run: npm install -D "vuepress-plugin-md-enhance@next"

    - run: npm run docs:build -- vuepress build docs

    - run: echo 'github.moonLord.cn' > 'docs/.vuepress/dist/CNAME'



    # https://github.com/MoonLord-LM/MyJava

    - run: mkdir -p 'tmp/maven/MoonLord-LM/MyJava'
    - run: git clone 'https://github.com/MoonLord-LM/MyJava.git' 'tmp/maven/MoonLord-LM/MyJava'

    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/super-parent/pom.xml"
    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/version-management-bouncy-castle/pom.xml"
    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/version-management-groovy/pom.xml"
    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/version-management-tomcat/pom.xml"
    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/parent/pom.xml"
    - run: mvn -B -U -e install --file "tmp/maven/MoonLord-LM/MyJava/pom.xml"

    - run: mkdir -p 'docs/.vuepress/dist/maven/cn/'
    - run: mv '/home/runner/.m2/repository/cn/moonlord' 'docs/.vuepress/dist/maven/cn/'



    # https://github.com/crazy-max/ghaction-github-pages
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: docs/.vuepress/dist
        target_branch: github-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
